# Generated by Django 4.2.5 on 2024-01-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('longitude', models.CharField(verbose_name=100)),
                ('latitude', models.CharField(verbose_name=100)),
                ('category', models.CharField(verbose_name=200)),
                ('phoneNumber', models.CharField(verbose_name=20)),
                ('link', models.TextField()),
            ],
        ),
    ]
