# Generated by Django 4.2.5 on 2024-01-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='category',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partners',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partners',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='partners',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
