# Generated by Django 4.2.5 on 2023-10-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_track',
            field=models.DateTimeField(default=None),
        ),
    ]
