# Generated by Django 4.2.5 on 2023-10-14 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_date_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_track',
        ),
    ]
