# Generated by Django 4.2.5 on 2023-10-24 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('errorCode', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmw',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dodge',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ford',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gm',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gmc',
            name='category',
        ),
        migrations.RemoveField(
            model_name='honda',
            name='category',
        ),
        migrations.RemoveField(
            model_name='hyundai',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jeepandchrysler',
            name='category',
        ),
        migrations.RemoveField(
            model_name='kia',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mazda',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mitsubishi',
            name='category',
        ),
        migrations.RemoveField(
            model_name='nissan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='category',
        ),
        migrations.RemoveField(
            model_name='toyota',
            name='category',
        ),
        migrations.DeleteModel(
            name='Audi',
        ),
        migrations.DeleteModel(
            name='Bmw',
        ),
        migrations.DeleteModel(
            name='Dodge',
        ),
        migrations.DeleteModel(
            name='Ford',
        ),
        migrations.DeleteModel(
            name='Gm',
        ),
        migrations.DeleteModel(
            name='Gmc',
        ),
        migrations.DeleteModel(
            name='Honda',
        ),
        migrations.DeleteModel(
            name='Hyundai',
        ),
        migrations.DeleteModel(
            name='JeepAndChrysler',
        ),
        migrations.DeleteModel(
            name='Kia',
        ),
        migrations.DeleteModel(
            name='Mazda',
        ),
        migrations.DeleteModel(
            name='Mitsubishi',
        ),
        migrations.DeleteModel(
            name='Nissan',
        ),
        migrations.DeleteModel(
            name='Ram',
        ),
        migrations.DeleteModel(
            name='Toyota',
        ),
    ]
