# Generated by Django 4.2.5 on 2024-01-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.package')),
            ],
        ),
    ]
